### In container
# iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
# echo 1 > /proc/sys/net/ipv4/ip_forward

### On client
# 172.21.0.0/16 is the intra containers network
# sudo route -n add -net 172.21.0.0/16 172.16.0.1

### sample conf on osx
# sudo route -n delete -net 172.21.0.0/16 172.16.0.1
# sudo route -n add -net 172.21.0.0/16 172.16.0.1
# networksetup -setdnsservers Wi-Fi 8.8.8.8,172.21.0.10

version: "3.9"
services:
  rospo:
    build: .
    command: >
      bash -c "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
      rospo sshd -A a"
    privileged: true
    ports:
      - "2222:2222"
      - "8800:8800"
  web:
    image: nginx